### ISSUE TITLE
Enhancement: work with rclone union remotes & remove sa from remote

### ISSUE THREAD

**Issue by edrock200** [Visorask/sarotate#10]
Thanks for making this awesome utility!

Two enhancement requests for consideration:
1. Support changing service account on underlying remote of a union remote which appears to be supported by rclone:
https://forum.rclone.org/t/edit-service-account-while-mounted/15760/
Specific post with command:
https://forum.rclone.org/t/edit-service-account-while-mounted/15760/104
2. Is there a way to remove the service account from the remote so it falls back to it's oauth key/secret/token, preferably a script we could add to execstop on the service to put the remote back to it's default state without any sa's attached or without the need to remount so our dir cache stays in tact?
3. Thanks again and thanks for your consideration and time.
4. Ed

**Comment by Visorask** [comment]
1. This is already supported you just need to define the names of each remote with the same port for the union mount.
So for instance instead of this:
```
main:
  remote:
   - teamdrive1
   - teamdrive2
   - teamdrive3
   - teamdrive4
  port:
   - 5572
   - 5573
   - 5574
   - 5575   
```
It would be this:
```
main:
  remote:
   - teamdrive1
   - teamdrive2
   - teamdrive3
   - teamdrive4
  port:
   - 5572
   - 5572
   - 5572
   - 5572   
```
2. There is a way but not through my script. You would need an outside script or to adjust my script to fit that need.
