### ISSUE TITLE
Issues at first run

### ISSUE THREAD

**Issue by atmos-o** [Visorask/sarotate#11]
rclone mount is named "rc". Have 8 SA creds saved & named as 1 through 8. For this test I commented out all remotes but first one.

I also edited my rclone service file with:
```
--rc-no-auth \
--rc-addr=localhost:5572 \
```

```
$ ./sarotate -c config.yml

<14>Mar 20 14:23:07 sarotate: ====> BEGIN LOGGING
<14>Mar 20 14:23:07 sarotate:yyq_detect: Checking if version is 3.4.1.
<14>Mar 20 14:23:07 sarotate:yyq_detect: yyq is at version 3.4.1.
<14>Mar 20 14:23:07 sarotate:yyq_detect: Version check complete.
**********************************************
**                                          **
**          SARotate Version 3.3            **
**                                          **
**       Written by Lex and Visorak         **
**   https://github.com/Visorask/sarotate   **
**                                          **
**********************************************
<14>Mar 20 14:23:08 sarotate:main_rotate: SA Rotate is now initializing.
logger: invalid option -- '>'
Try 'logger --help' for more information.
<14>Mar 20 14:23:08 sarotate:log_rotate: Skipping log rotation: /opt/sarotate/logs/sarotate.log < 1048576
<14>Mar 20 14:23:08 sarotate:main_rotate: Switching remote rc to use service account 0.json for 15m.
2021/03/20 14:23:08 Failed to rc: connection failed: Post "http://127.0.0.1:5572/backend/command": dial tcp 127.0.0.1:5572: connect: connection refused
<14>Mar 20 14:23:08 sarotate:main_rotate: SARotate will now go idle for 15m.
```

**Comment by Visorask** [comment]
Hmm it's trying to use `0.json` which it should not do as you have set 1-8 as your min and max yeah?
Post your `config.yml` here with any sensitive information replaced with random stuff.

**Comment by atmos-o** [comment]
Correct. I also modified my rclone systemd to include 
`--rc-no-auth \`
`--rc-addr=localhost:5572 \`

And this is my config file

```
rclone:
  rclone_config: "$HOME/.config/rclone/rclone.conf"
  rc_user: "user"
  rc_pass: "pass"
  ip: 127.0.0.1
global:
  minsa: 1
  maxsa: 50
  nextsa: 101
  json_dir: "/opt/sarotate/accounts/"
  sleeptime: 15m
  same_sa: off
log:
  logr_name: "sarotate"
  logr_dir: "/opt/sarotate/logs"
  logr_size: 1
  logr_detail: verbose
  log_level: ERROR
apprise:
  notif: off
  disc_id: "{WebhookID}/{WebhookToken}"
  slack_id: "{tokenA}/{tokenB}/{tokenC}"
  pushover_id: "{user_key}@{token}"
main:
  remote:
   - rc
  port:
   - 5572
```

**Comment by Visorask** [comment]
Set your:
```
minsa: 1
maxsa: 8
nextsa: 1
```
As you only have 8 SA's you need to have those set correctly. And also `nextsa` is only set at `101` if you are using thousands of SA's across many projects.
Also make sure to reload your service file for your mount if you haven't already.

**Comment by atmos-o** [comment]
sorry. I copied the uncommented file to not post so much. Forgot to modify that when sending it here. But I did originally change those values and got this same output.

**Comment by atmos-o** [comment]
if it makes a difference. I didn't use safire. Came across errors on that so manually created those SA accounts

**Comment by Visorask** [comment]
Alright it probably is something in my math. Are you using the `-f` first-run? option?

**Comment by atmos-o** [comment]
I used the `-f` flag and got the same response. I tried going to rclone and enabling webGUI but came back with nothing. Could that be indicating an issue with rclones rc? Can I do anything to make sure it is not Rclones issue?

**Comment by Visorask** [comment]
It may just be my code logic. Have not had a chance to test any and won't until tomorrow. I don't think it is on your end.

**Comment by Chudz** [comment]
I think im having a simlair issue:

config:
```
global:
  minsa: 1
  maxsa: 10
  nextsa: 1
  json_dir: "/opt/service-accounts"
```

error:
```
<14>Apr 27 13:38:53 sarotate: ====> BEGIN LOGGING
<14>Apr 27 13:38:53 sarotate:yyq_detect: Checking if version is 3.4.1.
<14>Apr 27 13:38:53 sarotate:yyq_detect: yyq is at version 3.4.1.
<14>Apr 27 13:38:53 sarotate:yyq_detect: Version check complete.
<11>Apr 27 13:38:54 sarotate:array_combine: Service account 0 is outside the minsa: 1 and maxsa: 10 set in the config file.
<11>Apr 27 13:38:54 sarotate:array_combine: Correct this and run the script again.
<11>Apr 27 13:38:54 sarotate:array_combine: The script will now exit.
```

```
/opt/sarotate$ ./renamer -f /opt/service-accounts/
1.json  2.json  3.json  4.json  5.json  6.json  7.json  8.json  9.json  10.json
```
