### ISSUE TITLE
Failed to rc: Failed to read rc response: 500 Internal Server Error

### ISSUE THREAD

**Issue by Aerya** [Visorask/sarotate#5]
EDIT OMG, forgot about your warn. I'm reloading all configs to see whats going on.
Well mounts are but I still got the error.

Hi,

Thanks for the script but it seems I misunderstood it or my config is bad. I want to use sarotate to push up more than 750GB daily to my teamdrive.

Here are the logs:
```
2020-10-27:11:06:02 INFO    /opt/sarotate/sarotate:73 SARotate will now go idle for 15m.
2020-10-27:11:10:32 INFO    /opt/sarotate/sarotate:63 SA Rotate is now initializing these mounts, starting with /home/aerya/outils/safiles/1.json with an increment of 1.
2020-10-27:11:10:32 INFO    /opt/sarotate/sarotate:67 Switching remote g5crypt to use service account 1.json for 15m
Failed to rc: Failed to read rc response: 500 Internal Server Error: {
	"error": "command \"set\" failed: command not found",
	"input": {
		"command": "set",
		"fs": "g5crypt:",
		"opt": {
			"service_account_file": "/home/aerya/outils/safiles/1.json"
		}
	},
	"path": "backend/command",
	"status": 500
}
2020-10-27:11:10:32 INFO    /opt/sarotate/sarotate:67 Switching remote g6crypt to use service account 2.json for 15m
Failed to rc: Failed to read rc response: 500 Internal Server Error: {
	"error": "command \"set\" failed: command not found",
	"input": {
		"command": "set",
		"fs": "gHDO6crypt:",
		"opt": {
			"service_account_file": "/home/aerya/outils/safiles/2.json"
		}
	},
	"path": "backend/command",
	"status": 500
}
2020-10-27:11:10:32 INFO    /opt/sarotate/sarotate:73 SARotate will now go idle for 15m.

```

My mounts: 
```
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/root/.config/rclone/rclone.conf
KillMode=none
RestartSec=5
ExecStart=/usr/bin/rclone mount g5crypt: /home/aerya/mnt/mounts/g5crypt --allow-other --allow-non-empty --log-level INFO --rc --rc-addr :5572 --rc-no-auth --log-file /home/aerya/outils/logs/mounts/g5crypt.log --poll-interval 15s --umask 002 --user-agent=myuag5 --cache-dir=/cache --vfs-cache-mode full --vfs-cache-max-size 50G --vfs-cache-max-age 1000h
ExecStop=/bin/fusermount -uz /home/aerya/mnt/mounts/g5crypt
ExecStartPost=/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr 0.0.0.0:5572 _async=true
Restart=on-failure

[Install]
WantedBy=multi-user.target

```
```
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/root/.config/rclone/rclone.conf
KillMode=none
RestartSec=5
ExecStart=/usr/bin/rclone mount g6crypt: /home/aerya/mnt/mounts/g6crypt --allow-other --allow-non-empty --log-level INFO --rc --rc-addr :5573 --rc-no-auth --log-file /home/aerya/outils/logs/mounts/g6crypt.log --poll-interval 15s --umask 002 --user-agent=myuag6 --cache-dir=/cache --vfs-cache-mode full --vfs-cache-max-size 50G --vfs-cache-max-age 1000h
ExecStop=/bin/fusermount -uz /home/aerya/mnt/mounts/g6crypt
ExecStartPost=/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr 0.0.0.0:5573 _async=true
Restart=on-failure

[Install]
WantedBy=multi-user.target

```

And my config file for sarotate:
```
# General rclone variables.
rclone:
  # Default rclone config. Change this if you have a non-standard rclone config location.
  rclone_config: "root/.config/rclone/rclone.conf"
  # Match rclone rc mount user and pass. If you use --no-auth then leave as default.
  rc_user: "user"
  # Match rclone rc mount user and pass. If you use --no-auth then leave as default.
  rc_pass: "pass"
  # Default is localhost/127.0.0.1 but you can change this to match your IP for RC.
  ip: 127.0.0.1
# Global variables
global:
  # Minimum json file that you want to use.
  minjs: 1
  # Maximum json file that you want to use.
  maxjs: 20
  # Use 1 or 101.  101 will split API usage to separate projects, but needs many service accounts.
  nextjs: 1
  # Location of the directory with your service account files.
  json_dir: "/home/aerya/outils/safiles"
  # Time the script will sleep for until running again.
  sleeptime: 15m
# Log variables
log:
  # Directory for logs.
  log_dir: "/home/aerya/outils/logs/"
  # Name of log file.
  log_file: "/home/aerya/outils/logs/sarotate.log"
  # Set NOTIF="key" , "all" or "none". Key includes errors.
  notif: "none"
  # Simple apprise command. Edit to taste.
  notif_cmd: "apprise"
# When filling these out you need to make sure the order of remote/port goes together or else
# the script will read wrong input/output and give errors.
main:
  remote:
   - g5crypt
   - g6crypt
  port:
   - 5572
   - 5573
```

Any tip/advice would be appreciated!
